export const DATA_SOURCE = 'DATA_SOURCE';
export const POLICIES_REPOSITORY = 'POLICIES_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const AGREEMENTS_REPOSITORY = 'AGREEMENTS_REPOSITORY';
export const VERIFICATIONS_REPOSITORY = 'VERIFICATIONS_REPOSITORY';
export const COMPANIES_REPOSITORY = 'COMPANIES_REPOSITORY';
export const SUBS_REPOSITORY = 'SUBS_REPOSITORY';
export const NEST_LOADER_CONTEXT_KEY = 'NEST_LOADER_CONTEXT_KEY';
