export const DATA_SOURCE = 'DATA_SOURCE';
export const POLICIES_REPOSITORY = 'POLICIES_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const AGREEMENTS_REPOSITORY = 'AGREEMENTS_REPOSITORY';
